#!/bin/bash

. ~/.genpatchesrc
if [[ ${#@} != 2 ]] ; then
	echo ">>> USAGE: gpcreatebranch <old-version> <new-version>"
	echo "This will create <new-version> from <old-version>"
	exit -1
fi

echo ">>> Going to copy genpatches-2.6/trunk/$1 to genpatches-2.6/trunk/$2 and instant commit. Press enter to continue"
read

svn copy svn+ssh://${USERNAME}@svn.gentoo.org/var/svnroot/linux-patches/genpatches-2.6/trunk/$1 svn+ssh://${USERNAME}@svn.gentoo.org/var/svnroot/linux-patches/genpatches-2.6/trunk/$2 -m "Creating $2 branch from $1"

