#!/bin/bash

. ~/.genpatchesrc

cd ${WEB_LOCAL}
./makesite.pl

rsync --exclude=/trunk --exclude=/tarballs --delete -Cavze ssh \
	${WEB_LOCAL}/output/ ${USERNAME}@${WEB_GENPATCHES_BASE}
rsync --delete -Cavze ssh ${LOCAL_PATCHES_TRUNK}/ ${USERNAME}@${WEB_GENPATCHES_BASE}/trunk
rsync -avz ${USERNAME}@dev.gentoo.org:/space/distfiles-local/${KERNEL_NAME}* ${WEB_LOCAL}/tarballs/
rsync -Cavze ssh ${WEB_LOCAL}/tarballs/ ${USERNAME}@${WEB_GENPATCHES_BASE}/tarballs


