#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Script expects version parameter. Exiting"
    exit -1
fi

. ~/.genpatchesrc

name="${ECHANGELOG_USER%<*}"
email="${ECHANGELOG_USER#*<}"
email="${email%>}"

cd ${WEB_LOCAL}
perl email-announcement.pl $1 ${KERNEL_NAME} ${LOCAL_TMP} ${REMOTE_BASE} |
	${SENDMAIL} -F \"${name}\" -f \"${email}\" gentoo-kernel@lists.gentoo.org


