#!/bin/bash

. ~/.genpatchesrc

PATCHES="$(ls ${LOCAL_PATCHES_TRUNK}/$1/*.patch)"
for i in ${PATCHES} ; do
	short="${i##*/}"
	code="${short:0:4}"

	if [[ $code -lt $2 ]] ; then
		continue
	fi

	echo ">>> Import: ${short}"
	if ! quilt import ${i}; then
		echo ">>> Failed to import ${short}"
		exit 1
	fi
	echo ">>> Push: ${short}"
	if ! quilt push; then
		echo ">>> Patch ${short} fails to push"
		exit 1
	fi
done
echo ">>> Done"
