#!/bin/bash
set -e

dst="$(readlink -f "wireguard-backport-5.4.y.patch")"
temp="$(mktemp -d)"
trap 'cd /; rm -rf "$temp";' INT TERM EXIT
cd "$temp"
echo "[+] Fetching patch for 5.4.y"
curl -# -f -L -o git-patches.mbox "https://git.zx2c4.com/wireguard-linux/patch/?id2=gregkh/stable-5.4.y&id=backport-5.4.y"
echo "[+] Normalizing patch"
splitdiff -a -p 1 git-patches.mbox
l=/dev/null
for patch in *.patch; do
	combinediff -q -p 1 "$l" "$patch" > next.patch
	l=last.patch
	mv next.patch last.patch
done
mv last.patch "$dst"
echo "[+] Result is in $dst"
